# Generated by Django 2.2.4 on 2019-09-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='checkedout_by',
            new_name='checked_out_by',
        ),
    ]
