# Generated by Django 2.2.4 on 2019-08-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owner',
            new_name='creator',
        ),
    ]
