# Generated by Django 2.2.6 on 2019-10-07 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190927_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checked_out_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
